package com.iot.locallization_ibeacon.myapplication;

import android.app.Activity;
import android.os.Bundle;
import android.util.Log;
import android.view.Menu;
import android.view.MenuItem;
import android.view.View;
import android.webkit.WebSettings;
import android.webkit.WebView;
import android.webkit.WebViewClient;

import com.google.android.glass.view.WindowUtils;
import com.google.android.glass.widget.CardBuilder;
import com.google.android.glass.widget.CardScrollView;

/**
 * An {@link Activity} showing a tuggable "Hello World!" card.
 * <p/>
 * The main content view is composed of a one-card {@link CardScrollView} that provides tugging
 * feedback to the user when swipe gestures are detected.
 * If your Glassware intends to intercept swipe gestures, you should set the content view directly
 * and use a {@link com.google.android.glass.touchpad.GestureDetector}.
 *
 * @see <a href="https://developers.google.com/glass/develop/gdk/touch">GDK Developer Guide</a>
 */
public class MainActivity extends Activity {

    /**
     * {@link CardScrollView} to use as the main content view.
     */
    private CardScrollView mCardScroller;

    /**
     * "Hello World!" {@link View} generated by {@link #buildView()}.
     */
    private View mView;

    @Override
    protected void onCreate(Bundle bundle) {
        super.onCreate(bundle);
      //  setContentView(mCardScroller);
        getWindow().requestFeature(WindowUtils.FEATURE_VOICE_COMMANDS);
        setContentView(R.layout.activity_main_activity2);

        WebView web =(WebView) findViewById(R.id.webView);
        WebSettings settings = web.getSettings();

        settings.setJavaScriptEnabled(true);
        settings.setBuiltInZoomControls(true);
        settings.setSupportZoom(true);

        web.getSettings().setCacheMode(WebSettings.LOAD_NO_CACHE);
        //settings.setAppCacheEnabled(false);
        web.loadUrl("javascript:document.body.style.zoom=0.5;");

    //    web.loadUrl("http://172.19.13.9/zjjnavigation/position.html");
        web.loadUrl("file:///android_asset/html/position.html");

        web.setWebViewClient(new WebViewClient() {
            @Override
            public boolean shouldOverrideUrlLoading(WebView view, String url) {
                // TODO Auto-generated method stub
                view.loadUrl(url);
                return true;
            }
        });
        web.setInitialScale(45);
       // web.loadUrl("javascript:document.body.style.zoom=0.3;");
    }

    @Override
    public boolean onCreatePanelMenu(int featureId, Menu menu) {
        if (featureId == WindowUtils.FEATURE_VOICE_COMMANDS) {
            getMenuInflater().inflate(R.menu.menu, menu);
            return true;
        }
        // Pass through to super to setup touch menu.
        return super.onCreatePanelMenu(featureId, menu);
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        getMenuInflater().inflate(R.menu.menu, menu);
        return true;
    }

    private float scale =1;
    @Override
    public boolean onMenuItemSelected(int featureId, MenuItem item) {
        Log.e("onMenuItemSelected", "onMenuItemSelected");

        if (featureId == WindowUtils.FEATURE_VOICE_COMMANDS) {
            String url = "";
            WebView web =(WebView) findViewById(R.id.webView);

            Log.e("onMenuItemSelected", "FEATURE_VOICE_COMMANDS");
            switch (item.getItemId()) {
                case R.id.baidu_menu_item:
                    url = "http://www.baidu.com";
                    web.loadUrl(url);
                    Log.e("baidu_menu_item", url);
                    break;
                case R.id.google_menu_item:
                    url = "http://www.goolge.com";
                    web.loadUrl(url);
                    Log.e("google_menu_item", url);
                    break;
                case R.id.lb_menu_item:
                    url = "http://www.yahoo.com";
                    web.loadUrl(url);
                    Log.e("google_menu_item", url);
                    break;

                case R.id.big_menu_item:
                    scale = scale+  0.1f;
                    web.loadUrl("javascript:document.body.style.zoom="+scale+";");
                   // web.zoomIn();

                    break;
                case R.id.small_menu_item:

                    scale = scale-  0.5f;
                    web.loadUrl("javascript:document.body.style.zoom=" + scale + ";");

                    break;
                default:
                    break;
            }

            return true;
        }
        // Good practice to pass through to super if not handled
        return super.onMenuItemSelected(featureId, item);
    }



    @Override
    protected void onResume() {
        super.onResume();
   //     mCardScroller.activate();
    }

    @Override
    protected void onPause() {
    //    mCardScroller.deactivate();
        super.onPause();
    }

    /**
     * Builds a Glass styled "Hello World!" view using the {@link CardBuilder} class.
     */
    private View buildView() {
        CardBuilder card = new CardBuilder(this, CardBuilder.Layout.TEXT);

        card.setText(R.string.hello_world);
        return card.getView();
    }

}
